// eslint-disable-next-line no-unused-vars
const data = [
  {
    id: 2,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 3,
    title: 'Ноутбук Acer',
    desk: 'Одна из наиболее распространенных – по размерам диагонали дисплея (бывают от 7 до 17 дюймов и больше).',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 4,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 5,
    title: 'Ноутбук Acer',
    desk: 'Вот об этой классификации мы и поговорим более детально: рассмотрим все основные виды и типы ноутбуков и разберемся, кому и какое устройство подойдет лучше всего.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 6,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 7,
    title: 'Ноутбук Acer',
    desk: 'Одна из наиболее распространенных – по размерам диагонали дисплея (бывают от 7 до 17 дюймов и больше). Вторая, более информативная, система базируется на технических характеристиках и назначении устройства. ',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 8,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 9,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 10,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 11,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 12,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 13,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
  {
    id: 14,
    title: 'Ноутбук Acer',
    desk: 'Ноутбук, в отличие от стационарного ПК, представляет собой портативное компактное устройство с предусмотренной функцией автономной работы, что позволяет использовать его вне дома или офиса.',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Schenker_VIA14_Laptop_asv2021-01.jpg/300px-Schenker_VIA14_Laptop_asv2021-01.jpg',
    price: '200000',
  },
];
